version: '3.7'
services:
  minio:
    image: minio/minio
    container_name: my-minio
    ports:
      - 9000:9000
      - 9090:9090
    environment:
      - MINIO_ROOT_USER=vivek
      - MINIO_ROOT_PASSWORD=vivek123
    volumes:
      - ~/minio/data:/data 
    command:
       server /data --console-address ":9090" 
  
volumes:
  minio:
    driver: local         
      
      
